servo_node:
  ros__parameters:
    moveit_servo:
      move_group_name: arm
      planning_frame: base_link
      ee_frame_name: lower_arm_link
      robot_link_command_frame: base_link
      command_in_type: speed_units

      command_out_topic: /servo_controller/commands
      command_out_type: std_msgs/Float64MultiArray

      publish_joint_positions: false
      publish_joint_velocities: true
      publish_joint_accelerations: false

      publish_period: 0.01
      low_latency_mode: false
      incoming_command_timeout: 0.1
      num_outgoing_halt_msgs_to_publish: 4

      scale:
        linear: 0.5
        rotational: 0.5
        joint: 1.0

      check_collisions: false

    robot_description_kinematics:
      arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
