moveit_servo:
  ros__parameters:

    move_group_name: arm
    planning_frame: base_link
    ee_frame_name: tool0

    publish_period: 0.01
    incoming_command_timeout: 0.5

    command_in_type: unitless

    scale:
      linear: 0.2
      rotational: 0.2
      joint: 0.5

    command_out_type: trajectory_msgs/JointTrajectory
    command_out_topic: /arm_controller/joint_trajectory

    publish_joint_positions: true
    publish_joint_velocities: true
    publish_joint_accelerations: false

    use_smoothing: true
    smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

    joint_command_in_topic: ~/delta_joint_cmds
    cartesian_command_in_topic: ~/delta_twist_cmds
    joint_topic: /joint_states
    status_topic: ~/status

    check_collisions: true
    collision_check_rate: 10.0

    self_collision_proximity_threshold: 0.01
    scene_collision_proximity_threshold: 0.02

    lower_singularity_threshold: 17.0
    hard_stop_singularity_threshold: 30.0
    leaving_singularity_threshold_multiplier: 2.0

    joint_limit_margins: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
