controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    servo_controller:
      type: velocity_controllers/JointGroupVelocityController


joint_state_broadcaster:
  ros__parameters: {}


servo_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    command_timeout: 0.2
    state_publish_rate: 50
